Article about 'Thinking in Traits'
corrode/corrode.github.io pull request #21
Opened 2024-05-13 13:28 UTC by mre

2024-05-13 14:23 UTC, M3t0r requested changes
Don't know about the title. Might need to workshop that. But the post is good!

But in the end it's more about iterators and a few neat tricks with the trait system, not really how you can "think in traits" and apply that to your own code. Maybe "leverage traits for simple code" or something along those lines. "Why traits are better than syntactic sugar"?

2024-05-13 14:23 UTC, M3t0r commented on content/blog/list-comprehensions/index.md
> +This is what this post is about.
"This" is a bit unclear. This revelation, this journey, this philosophy. Something like that.

Good intro otherwise.

2024-05-13 14:23 UTC, M3t0r commented on content/blog/list-comprehensions/index.md
> +This would be quite tricky to do with list comprehensions in Python.
Many "this" in the post ;-)

```suggestion
Achieving the same effect with list comprehensions in Python is quite tricky.
```

2024-05-13 14:23 UTC, M3t0r commented on content/blog/list-comprehensions/index.md
> +```
`set` is a bit weird, especially since it uses curly braces. Maybe a dict would be better? 🤷

2024-05-13 14:23 UTC, M3t0r commented on content/blog/list-comprehensions/index.md
> +# doesn't have a first letter
```suggestion
first_letters = Counter([band[0] for band in bands if len(band)])
```

ez

2024-05-13 14:33 UTC, mre commented on content/blog/list-comprehensions/index.md
> +# doesn't have a first letter
Thanks

2024-05-13 14:35 UTC, mre commented on content/blog/list-comprehensions/index.md
> +```
Wanted to show one of the lesser used datastructures for a change. The idea was to show that list comprehension are quite flexible.

2024-05-13 14:36 UTC, mre commented on content/blog/list-comprehensions/index.md
> +This would be quite tricky to do with list comprehensions in Python.
OK. I'll go through the article again and look for replacements.

2024-05-13 14:39 UTC, mre commented on content/blog/list-comprehensions/index.md
> +This is what this post is about.
Thanks. Done.

2024-05-13 16:13 UTC, M3t0r requested changes

2024-05-13 16:13 UTC, M3t0r commented on content/blog/list-comprehensions/index.md
> +This journey is what this post is about.
Still sounds weird :-/

2024-05-13 17:01 UTC, mre commented on content/blog/list-comprehensions/index.md
> +This journey is what this post is about.
Maybe I just remove it?

2024-05-13 17:04 UTC, mre commented on content/blog/list-comprehensions/index.md
> +This journey is what this post is about.
removed

2024-05-13 17:04 UTC, mre commented
Title was my fault, sorry. Real title is 'Thinking in Iterators'. Updated.

2024-05-14 22:48 UTC, mre commented
@prscheduler 15/05/2024T10:00

2024-05-15 10:00 UTC, merged