Podcast episode
corrode/corrode.github.io pull request #54
Opened 2024-11-27 20:27 UTC by mre

2024-11-27 20:27 UTC, mre commented
@prscheduler 28/11/2024T16:00

2024-11-27 22:11 UTC, M3t0r requested changes

2024-11-27 22:11 UTC, M3t0r commented on content/podcast/s03e04-gitbutler/index.md
> +- [Git Book - Plumbing and Porcelain](https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain) - Explaining "git porcelain", written by Scott
```suggestion
```

I cut the section that mentioned this.

2024-11-27 22:11 UTC, M3t0r commented on content/podcast/s03e04-gitbutler/index.md
> +- [I Will Survive](https://en.wikipedia.org/wiki/I_Will_Survive) - Gloria Gaynor's iconic song: "At first I was afraid, I was petrified"
I think the description explains too much :grinning: Also, I think the YouTube link would be more helpful to listeners.

2024-11-27 22:11 UTC, M3t0r commented on content/podcast/s03e04-gitbutler/index.md
> +- [Labradoodle](https://en.wikipedia.org/wiki/Labradoodle) - A dog breed
```suggestion
- [Labradoor](https://en.wikipedia.org/wiki/Labrador_Retriever) - A magical dog breed
```

I actually wrote down the wrong breed :facepalm:

2024-11-27 22:11 UTC, M3t0r commented on content/podcast/s03e04-gitbutler/index.md
> +
```suggestion

<div><script id="letscast-player-4553b0d1" src="https://letscast.fm/podcasts/rust-in-production-82281512/episodes/gitbutler-with-scott-chacon-and-kiril-videlov/player.js?size=s"></script></div>

```

2024-11-28 03:17 UTC, M3t0r requested changes

2024-11-28 03:17 UTC, M3t0r commented on content/podcast/s03e04-gitbutler/index.md
> +- [Labradoor](https://en.wikipedia.org/wiki/Labrador_Retriever) - A magical dog breed
```suggestion
- [Labrador](https://en.wikipedia.org/wiki/Labrador_Retriever) - A magical dog breed
```

It's right there in the link, and I still fucked up :-D

2024-11-28 09:35 UTC, mre commented on content/podcast/s03e04-gitbutler/index.md
> +- [I Will Survive](https://en.wikipedia.org/wiki/I_Will_Survive) - Gloria Gaynor's iconic song: "At first I was afraid, I was petrified"
true, changed

2024-11-28 09:38 UTC, mre commented
@prscheduler 28/11/2024T16:00

2024-11-28 16:01 UTC, merged